apiVersion: v1
kind: Secret
metadata:
  name: django-env
  namespace: django
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLTY4bjlxK19lckAqdSVjIXIybCprKWtjKWo9ZSVuQGY4cTh0eG1fcT05ZDJ0Z3h6YnF1
  DB_NAME: YWxhYmlu
  DB_USERNAME: Ym9va21hc3Rlcg==
  DB_HOST: MzQuNjQuMjQ1Ljk2
  DB_PORT: NTQzMg==
  # DB_HOST: MTAuMTc4LjAuMTM=
  DB_PASSWORD: YTUhJGFhQzYjd2Iz