# Generated by Django 4.0 on 2023-02-20 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=256)),
                ('publisher', models.CharField(max_length=256, null=True)),
                ('price', models.IntegerField(null=True)),
                ('cover', models.TextField(null=True)),
                ('toc', models.TextField(null=True)),
                ('category', models.CharField(max_length=64, null=True)),
                ('detail', models.TextField(null=True)),
                ('publish_date', models.DateField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookRank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('isbn', models.CharField(max_length=15, unique=True)),
                ('book_name', models.CharField(max_length=255)),
                ('review_count', models.IntegerField()),
                ('review_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('site', models.CharField(max_length=1)),
                ('period', models.CharField(max_length=11)),
                ('rank_date', models.CharField(max_length=9)),
                ('create_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
